.TH LOCALCI 1 2020-09-06 Serenity "User Commands"

.SH NAME
localci \- Build a range of commits

.SH SYNOPSIS
.SY localci
.OP --help
.OP --version
[\fB--\fR]
.IR commit ...
.YS

.SH DESCRIPTION
Checks out all provided commits and runs the build command.
If all builds are successful, switches back to the originally checked out revision.
Otherwise, stops at the first unsuccessful build and leaves the repository in a detached state.
.P
The commits are directly passed to \fBgit rev-list\fR so ranges like \fBmaster..HEAD\fR are allowed.

.SH OPTIONS
.TP
.BR --help
Output help information and exit.
.TP
.BR --version
Output version information and exit.

.SH EXAMPLES

localci master..HEAD

localci 55c486637 foo..bar
